name: syntreenet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h6cacc03_7
  - brotli=1.1.0=hd590300_0
  - brotli-bin=1.1.0=hd590300_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.16.0=ha00ac49_1009
  - certifi=2024.7.4=py39h06a4308_0
  - cffi=1.15.1=py39h7a31438_5
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda-pack=0.7.1=py39h06a4308_0
  - contourpy=1.1.1=py39h7633fee_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.4.1=h8ab8bb3_9
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.8.1=py39h3d6467e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - faiss-gpu=1.7.4=py3.9_hc0239a3_0_cuda11.4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2023.9.2=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.5=py39h03b5d36_0
  - greenlet=2.0.2=py39h3d6467e_1
  - icu=69.1=h9c3ff4c_0
  - importlib-resources=6.1.0=pyhd8ed1ab_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_0
  - libbrotlidec=1.1.0=hd590300_0
  - libbrotlienc=1.1.0=hd590300_0
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.19=hd590300_0
  - libexpat=2.5.0=hcb278e6_1
  - libfaiss=1.7.4=h13c3c6d_0_cuda11.4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=12_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.18.3=h6239696_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.9.14=haae042b_4
  - libzlib=1.2.13=hd590300_5
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - matplotlib-base=3.8.0=py39he9076e7_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7f8727e_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - ninja=1.11.1=h924138e_0
  - numpy=1.26.0=py39h474f0d3_0
  - ocl-icd=2.3.2=h5eee18b_1
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py39h71cce9b_4
  - openjpeg=2.5.0=h488ebb8_3
  - openmm=8.0.0=py39he81762f_4
  - openssl=3.3.0=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.1=py39hddac248_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py39h444a776_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycairo=1.24.0=py39hc92de75_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytorch=1.12.1=cpu_py39he8d8e81_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=26.0.2=py39ha1047a2_0
  - readline=8.2=h8228510_1
  - reportlab=4.0.4=py39hd1e30aa_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlalchemy=2.0.21=py39hd1e30aa_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.7.0=h924138e_0
  - tk=8.6.13=h2797004_0
  - torchmetrics=1.2.0=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py39hd1e30aa_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - cachetools==5.3.2
      - charset-normalizer==3.2.0
      - click==7.1.2
      - cloudpickle==3.0.0
      - colorful==0.5.6
      - configargparse==1.7
      - dataclasses==0.6
      - dill==0.3.7
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - fastjsonschema==2.19.1
      - fcd==1.2.2
      - fcd-torch==1.0.7
      - filelock==3.12.4
      - frozenlist==1.4.0
      - fuzzywuzzy==0.18.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.19.0
      - google-auth==2.23.3
      - google-auth-oauthlib==1.1.0
      - googleapis-common-protos==1.63.0
      - grpcio==1.59.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.11.0
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-metadata==6.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - linkify-it-py==2.0.3
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markdown-mermaid-to-images==0.3.0.post1
      - markupsafe==2.1.3
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - memray==1.12.0
      - msgpack==1.0.8
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbformat==5.10.4
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - panflute==1.12.5
      - pathos==0.3.1
      - plotly==5.22.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - prometheus-client==0.20.0
      - proto-plus==1.23.0
      - psutil==5.9.6
      - py-spy==0.3.14
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeprecate==0.3.2
      - pypandoc==1.13
      - pyscreener==1.1.1
      - pytdc==0.4.1
      - pytorch-lightning==2.1.1
      - ray==2.22.0
      - rdkit==2023.9.5
      - rdkit-pypi==2022.9.5
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.11.2
      - seaborn==0.12.2
      - sentry-sdk==2.2.0
      - setproctitle==1.3.3
      - smart-open==7.0.4
      - smmap==5.0.1
      - tenacity==8.3.0
      - tensorboard==2.15.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - textual==0.62.0
      - threadpoolctl==3.2.0
      - torch==2.1.0
      - torch-geometric==2.4.0
      - triton==2.1.0
      - uc-micro-py==1.0.3
      - urllib3==2.0.5
      - virtualenv==20.26.2
      - wandb==0.17.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - yarl==1.9.2
      - zss==1.2.0
prefix: /home/msun415/miniconda3/envs/synnet
